# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


title: Hikes and Food
author: Luca
description: Hikes and Food, my 2 passions.

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Tags
    url: /tags/
  - text: Download
    url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# Colors
accent_color: '#FA5F55'

# Site footer
# footer:
#  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes]
# (https://www.justgoodthemes.com)."
#  has_social: true

# Permalinks
permalink: /:title

# Sass
sass:
  sass_dir: _sass
  style: compressed